dmn-tck/tck

- TestCases/compliance-level-2/0100-feel-constants/0100-feel-constants-test-01.xml
- TestCases/compliance-level-2/0100-feel-constants/0100-feel-constants.dmn
- TestCases/compliance-level-2/0101-feel-constants/0101-feel-constants-test-01.xml
- TestCases/compliance-level-2/0101-feel-constants/0101-feel-constants.dmn
- TestCases/compliance-level-2/0102-feel-constants/0102-feel-constants-test-01.xml
- TestCases/compliance-level-2/0102-feel-constants/0102-feel-constants.dmn
I am proposing we use tests numbers starting with 0100 and up for our extensive FEEL tests. We can leave the lower numbers to use with more adhoc tests as we've been doing.
In any case, test numbers are only really used to make sure we have unique IDs for the tests. All the reporting is done by labels.
> Adding tests for FEEL constants

- runners/dmn-tck-runner-drools/pom.xml
- runners/dmn-tck-runner/src/main/java/org/omg/dmn/tck/runner/junit4/DmnTckRunner.java
- runners/dmn-tck-runner/src/main/java/org/omg/dmn/tck/runner/junit4/DmnTckVendorTestSuite.java
* Result filename is configurable by overriding
'DmnTckVendorTestSuite.getResultFileName()'
* Defaults to result.csv
* Returning null disables result file creation 
Background: We would like to integrate the tck testsuite as part of our
unit tests and test our dmn engine with different settings against the
tck.  
For that, we would like to have result file name to be customizable (so
that multiple files can be written and placed into target folder) and
also a way to disable it.
* Updated drools to release version 7.1.0.Final so that artifacts can be fetched from maven central
> Configurable name for result.csv

- runners/dmn-tck-runner/src/main/java/org/omg/dmn/tck/runner/junit4/DmnTckVendorTestSuite.java
Our test reporter expects a file called 'tck_results.csv'. Let's make that the default in order to ease submissions.
> Match result file name with reporter expectations

- runners/dmn-tck-runner/pom.xml
- runners/dmn-tck-runner/src/main/java/org/omg/dmn/tck/runner/junit4/DmnTckRunner.java
- runners/dmn-tck-runner/src/main/java/org/omg/dmn/tck/runner/junit4/TestResult.java
- runners/dmn-tck-runner/src/test/java/org/omg/dmn/tck/runner/junit4/TestResultTest.java
'Lines' can now be added to TestResult, so that a more detailed result
can produced and printed, showing in detail why a test failed. For
example, one line for each failed comparison of expected and actual
result.
> Extended TestResult object with 'lines'

- TestCases/compliance-level-2/0101-feel-constants/0101-feel-constants-test-01.xml
- TestCases/compliance-level-2/0102-feel-constants/0102-feel-constants-test-01.xml
- TestCases/compliance-level-2/0105-feel-math/0105-feel-math-test-01.xml
- TestCases/compliance-level-3/0002-string-functions/0002-string-functions-test-01.xml
- TestCases/compliance-level-3/0002-string-functions/0002-string-functions.dmn
- TestResults/Camunda/7.7.0/tck_results.csv
Currently, we have four test cases that combine many tests for different FEEL functions, arithmetics, and constant literals. If an implementation has issues in these areas, the current report does not show any details and it is really hard to even know which decision or FEEL feature caused a problem.
In order to make it easier for users to see which FEEL features are supported, we suggest a small split in the test case XML files. Each expected result of a decision should be distinguished as a separate test case and therefore gets reported separately. This also helps developers from software vendors to identify and fix issues in their tools.
This proposal keeps changes to a minimum and does not require the DMN files or the Test XML files to be split or duplicated.
Have a look at the …
> Split test cases of FEEL functions, constants and math (for better reporting)

- TestCases/testCases.xsd
Extended schema to add errorResult flag to ResultNode to indicate null-value as a result of an error situations
> Extended schema to provide marker for error results

- runners/dmn-tck-runner/src/main/java/org/omg/dmn/tck/runner/junit4/DmnTckRunner.java
Missing call is required to resume testing after one test case fails.
> Add missing call.

- TestCases/compliance-level-3/1117-feel-date-and-time-function/1117-feel-date-and-time-function-test-01.xml
- TestCases/compliance-level-3/1117-feel-date-and-time-function/1117-feel-date-and-time-function.dmn
- TestCases/compliance-level-3/1117-feel-date-and-time-function/Readme.md
1117-feel-date-and-time-function-test-01
for
case 57 : date and time("2012-12-24")
CURRENT expected: an error
SHOULD ACTUALLY expect: 2012-12-24T00:00:00 (date and time)
Should not be an error.
Accordingly to the spec `date and time` function can receive
just the date part,
FEEL spec printed page 131 " date time string – a string value
consisting of a date string value, as specified above, optionally
followed by the character "T" followed by a time string value
as specified above "
> Fix case 57 for 1117-feel-date-and-time-function-test-01

- TestCases/testCases.xsd
My contribution to issue #89 
Essentially, i'm proposing adding a targetBKM attribute to the existing testCase definition. This would hold the name of a BKM in the model.
You can then use inputNodes/resultNodes as you would normally, the only caveat is that there would be a single resultNode with the BKM name.
For instance the testcase 0001 would become if we would change the logic of _Greating Message_ to a BKM:
<testCase id="001" **targetBKM="Greeting Message"**>
<description>Testing valid input</description>
<inputNode name="Full Name">
<value>John Doe</value>
</inputNode>
<resultNode name="Greeting Message" **type="bkm"**>
<expected>
<value>Hello John Doe</value>
</expected>
</resultNode>
</testCase>
I've always considered the resultNode attribute _type_ to be optional and we don't …
> Added target BKM Test

- TestCases/testCases.xsd
In order to support an empty context as testcase result there was already a fix that removed the required attribute for the name. But this was not sufficient. We also have to specify that inside a component no nested component is needed. Added minOccurs="0" to component.
> Additional fix for expected empty context

- runners/dmn-tck-validation/pom.xml
- runners/dmn-tck-validation/src/test/java/org/omg/dmn/tck/validation/TestCasesFiles.java
- runners/pom.xml
..for both DMN model xml files and TestCase xml files.
We could have this under continuous integration automatically on the master branch and on proposed PRs, using Travis CI for this GitHub repo (dmn-tck/tck).
This should mitigate against the issue discussed during last TCK call (an xml file in this repo is not consistent with its Schema) and check all files are consistent with their _expected_ Schema. This is a Maven module guarded under a specific Maven Profile, so it would run only if explicitly activated and in order to NOT prevent site generation or vendor runners from executing despite some problems are detected.
> Proposal for an optional Validation module checking Schema

- .travis.yml
As per issue https://github.com/dmn-tck/tck/issues/157
Summary:
- **Option A** was chosen during tck meeting: the green/red mark will be affected just and ONLY based on validation. Result of engine runners will NOT affect the green/red mark on github pr page.
- Camunda runner was included following [this comment](https://github.com/dmn-tck/tck/issues/157#issuecomment-406737566)
/cc @etirelli kindly double-check for merge, please?
> Enable DMN engines TCK Runners during Continuous Integration

- utils/dmn-tck-packager/README.md
- utils/dmn-tck-packager/src/main/java/org/dmn/tck/packager/CommandLinePackager.java
- utils/dmn-tck-packager/src/main/java/org/dmn/tck/packager/Packager.java
Prevented a NPE on relative path, 
add modelName to extracted test cases 
optionally output a dmn file without the test cases on extraction
> Improvements to the TCK test packager/unpackager

- runners/dmn-tck-validation/pom.xml
- runners/dmn-tck-validation/src/test/java/org/omg/dmn/tck/validation/TestTestResultsContent.java
- runners/dmn-tck-validation/src/test/resources/log4j.properties
For each Vendor results directory:
- check only 1 version subdirectory
- that subdirectory to contain the `tck_results.csv` and `tck_results.properties` files
- minimal check `.properties` file is consistent
Further content check of both files will be performed later by the reporter runner, given we will be moving to automate website generation anyway.
This should mitigate the need to perform manual corrections like it was needed with f2535d780cda54c8188700aa11ec3da334bc7f7d
> Augment Validation runner to check Vendor's results dir for basic checks

- TestCases/compliance-level-3/0031-user-defined-functions/0031-user-defined-functions.dmn
Test had typeRef="tFnInvocationResult" in two places.  tFnInvocationResult in not defined in the model.  I had a flag to relax this stuff as I was working but, truth be told, it should not pass and is not a valid model.
The test is not a test for types so I have just removed the typeRefs.
> Test has invalid type "tFnInvocationResult"

- runners/dmn-tck-marshaller/pom.xml
Address CVE-2018-12022 regardless of the actual impact on TCK
website/infra
> Update jackson-databind version

- TestCases/compliance-level-3/0012-list-functions/0012-list-functions-test-01.xml
- TestCases/compliance-level-3/0012-list-functions/0012-list-functions.dmn
Some type fixes to align with v1.2 types (another v1.1 'singleton array' thing).
The summary: the list results are of mixed types and not pure string lists as the dmn specifies.  Likely was okay with 'singleton array' code but, truth be told, they are not string lists anymore.
The purpose of the test suite is testing lists, not types, so, I have simply removed the offending types.   
This was originally in the big 'consolidated' PR but got lost when we split them up.
Mentioned here: https://github.com/dmn-tck/tck/pull/204#issuecomment-448089266
And some discussion here: https://github.com/dmn-tck/tck/pull/204#issuecomment-452887856
> 0012-list-functions

- TestCases/compliance-level-3/0056-feel-modulo-function/0056-feel-modulo-function-test-01.xml
- TestCases/compliance-level-3/0056-feel-modulo-function/0056-feel-modulo-function.dmn
I am proposing the following alignments, and new tests, following DMN13-125. 
In short: align modulo function results for negative/non-integer with Spreadsheet-like system.
My perspective is that DMN13-125 clarifies behavior, even on DMNv1.2, for an unclear part of the spec. Hence I am raising this test cases now, in order to align with DMN13-125 clarifications.
> Align to DMN13-125 Disambiguation for Modulo / Remainder function

- TestCases/compliance-level-3/0090-feel-paths/0090-feel-paths-test-01.xml
- TestCases/compliance-level-3/0090-feel-paths/0090-feel-paths.dmn
Initial commit to cover feel paths on nested lists.  Only two tests covering the 'nested lists' example in the spec with the v1.2 corrections requested here: https://issues.omg.org/issues/DMN13-133 and with amendments noted here: https://github.com/dmn-tck/tck/issues/285.
Hopefully not too controversial.
EDIT: And thanks @tarilabs for the correction on the spec example.  Man, I stared at that thing for _ages_ trying to figure out what was supposed to happen - it totally fried my brain.  It didn't occur to me it was v1.1 singleton array type equality.  Doh!  After the correction things were pretty straight forward.  Thanks again.
> 0090-feel-paths

- TestCases/non-compliant/0019-flight-rebooking/0019-flight-rebooking.dmn
small update here to remove 'feel:' from typeRefs.  One typeref changed from string to number.  `Passenger1.Miles` is represented elsewhere in the model as a number.
```xml
<input id="b_Passenger_Priority_dt_i_P1_Miles" label="Passenger1.Miles">
<inputExpression typeRef="number">
<text>Passenger1.Miles</text>
</inputExpression>
</input>
```
> non-compliant: 0019-flight-rebooking

- TestCases/non-compliant/0015-all-any/0015-all-any.dmn
small update to remove 'feel:' from typeRefs.
Do we still need this in non-complaint?  We now have tests in lvl3 master covering this.
> non-compliant: 0015-all-any

- TestCases/non-compliant/0088-recursion/0088-recursion-test-01.xml
- TestCases/non-compliant/0088-recursion/0088-recursion.dmn
All, though the rebooking model in non-compliant exercises recursion, I thought it best to put in some specific tests.
The recursion here is in two flavours.  
One is a basic fibonacci test.  
The other is a little more interesting: it is recursive to depth-first traverse a tree structure, but also defines a typeRef that is 'self referencing' to create a tree type has children of the same type as itself.
The spec does not provide a 'well-formed' definition for ItemDefinition nor contains any references that I could find to it being acyclic so I am pretty sure a self-referencing structure is legal.
Comments welcome.
> non-compliant: 0088-recursion

- runners/dmn-tck-marshaller/pom.xml
Addresses CVE-2019-12086 although of moderate risk for this project
> Update com.fasterxml.jackson.core:jackson-databind to 2.9.9

- runners/dmn-tck-runner-drools/src/test/java/org/omg/dmn/tck/runner/drools/DroolsTCKTest.java
Avoid undesired runtime exception due to internal integrity typecheck
when a TCK test case leverages coercion
> Drools runner update (internals)

- runners/dmn-tck-runner/src/main/java/org/omg/dmn/tck/runner/junit4/DmnTckRunner.java
- runners/dmn-tck-runner/src/main/java/org/omg/dmn/tck/runner/junit4/DmnTckVendorTestSuite.java
Proposal for TCK infrastructure API changes to support multiple models.
This is to provide similarly to model under test URL, a collection of additional URL located in the same directory of the test case.
Please notice there is no change proposed to TCK xml file, in order to keep things simple.
I will comment on the limitations of other PRs for similar scope in the relevant PR page.
Adding at the same time test case `0086-import` to demonstrate.
> TCK infrastructure API changes to support multiple models, for DMN import features

- TestCases/compliance-level-3/0090-feel-paths/0090-feel-paths-test-01.xml
- TestCases/compliance-level-3/0090-feel-paths/0090-feel-paths.dmn
The actual balloted/approved proposal for DMN13-133 involves a different example which will end up in the new release of the spec. Augmenting the original test case with the actual example.
please note @StrayAlien original test do remain valid nevertheless, thanks again.
> Augment 0090-feel-paths with spec example from DMN13-133

- TestCases/compliance-level-3/0085-decision-services/0085-decision-services-test-01.xml
- TestCases/compliance-level-3/0085-decision-services/0085-decision-services.dmn
Re-done DS tests!  I really didn't quite 'get it' last time I submitted tests.  Hopefully this time I do.  :-)   
I have tested for both 'direct' invocation (calling it directly from the test suite like it was a 'microservice'), as well as 'indirect' (which is calling it from another DRG element - in this case, decisions).   The 'direct' tests are fairly separate in case this causes issues.  
... but, I think it is really worth asserting that a DS can be called as a root level element like a decision.  Hopefully that causes no issues with people's tests runners - mine required no alteration so hopefully others are the same.
I have asserted on similar stuff to normal BKM/functions, like correct params, no params, named params, badly-name params, too many params, incorrect type params. etc. …
> 0085-decision-services

- TestCases/compliance-level-3/0088-no-decision-logic/0088-no-decision-logic-test-01.xml
- TestCases/compliance-level-3/0088-no-decision-logic/0088-no-decision-logic.dmn
As previously discussed, a pragmatical example to address what was raised in https://github.com/dmn-tck/tck/issues/304
The DMN model is
Therefore in order to invoke the Decision Service correctly one must fulfil all the requirements, meaning the 2 Input Data and the single "Teacher's Evaluation" input Decision.
The "Teacher's Evaluation" input Decision has no defined decision logic in the DMN model file, and this is indeed intentional. 
All the 3 input requirements are provided by means of `<inputNode>` elements in the TCK test case file, as it was always allowed.
Although a synthetic model, I tried to model a plausible ~"real world" example model, with the intention to demonstrate where I do personally see a feasible and pragmatical application, besides what technically allowed by the …
> 0088-no-decision-logic

- TestCases/compliance-level-3/0012-list-functions/0012-list-functions.dmn
- TestCases/compliance-level-3/0086-import/0086-import.dmn
- TestCases/compliance-level-3/0088-no-decision-logic/0088-no-decision-logic.dmn
Happy new year all. 
Some small correctness changes to models.   No big deal - they just get caught in our verifier.  Let me know if I'm wrong.
0012-list-functions - diagram with an edge referencing an unknown id.  Edge Removed.
0086-import - DT annotation column with no name.  In xsd as optional but spec says in "8.3.2 Decision Table Input and Output metamodel" .. "A RuleAnnotationClause SHALL have a name".  I removed the annotations.
0088-no-decision-logic - Table 31 - "The OutputClause of a single output decision table SHALL NOT specify a typeRef".  Typeref is removed.
Greg.
> Small model cleanup

- TestCases/compliance-level-3/0092-feel-lambda/0092-feel-lambda-test-01.xml
- TestCases/compliance-level-3/0092-feel-lambda/0092-feel-lambda.dmn
a re PR of here: https://github.com/dmn-tck/tck/pull/357
A number of tests to verify usage of user-defined functions and Function Definitions as lambdas. Additionally, verification on usage and behaviour of closed over values ('closures') is included.
A few things to note:
- no 'function' typeRefs or item definitions have been used here - so this is within what is describable in v1.2.
- as a Decision may house any type of expression, in theory, it can also provide a lambda as a return value by using a user-defined function expression like function (a,b) a+b or a Function Definition expression. I'm not saying this is how people will use it, but tests are not about that - they're here to prove a mechanism works. To that end, a number of the tests here have a Decision returning a lambda.
- I …
> 0092-feel-lambda

- .github/workflows/global_validation.yml
- .github/workflows/optional_camunda.yml
- .github/workflows/optional_drools.yml
This PR is to migrate the current TravisCI settings:
https://github.com/dmn-tck/tck/blob/ee648ef0f9dfbe7c61ca95343b44d2c19bbceb08/.travis.yml#L6-L9
to GitHub Actions.
This is to avoid relying on Travis CI, which in the past year has not been very reliable to pick up webhooks and jobs from this repo.
Once GitHub Actions are merged, and in-place, we will eventually remove the Travis CI file.
> Migrate TravisCI settings to GitHub Actions

- TestCases/compliance-level-3/0082-feel-coercion/0082-feel-coercion.dmn
- TestCases/compliance-level-3/0086-import/Imported_Model.dmn
- TestCases/compliance-level-3/0087-chapter-11-example/0087-chapter-11-example.dmn
- TestCases/non-compliant/0019-flight-rebooking/0019-flight-rebooking.dmn
This is to address https://github.com/dmn-tck/tck/issues/376
There are 3 ways to address above:
- remove typeRef and let the implementation infer the type if needed
- set typeRef to Any
- set typeRef to a proper TFunctionItem introduced in DMN 1.3
This request removes the typeRefs to be consistent with existing test cases.
We need to add extra test cases for remaning options (Any or proper TFunctionItem).
> Fix variable.typeRef for BKMs

- docs/detail_ACTICO Platform_8.1.5.html
- docs/detail_Camunda BPM_7.13.0.html
- docs/detail_Digital Transformation Platform (DXP)_2.4.html
- docs/detail_Drools_7.51.0.Final.html
- docs/detail_OpenRules_7.0.0.html
- docs/detail_Oracle Process Cloud_17.3.3.html
- docs/detail_Trisotech Digital Enterprise Suite_10.6.0.html
- docs/detail_jDMN_3.4.1.html
- docs/glossary.html
- docs/index.html
- docs/overview_ACTICO Platform_8.1.5.html
- docs/overview_Camunda BPM_7.13.0.html
- docs/overview_Digital Transformation Platform (DXP)_2.4.html
- docs/overview_Drools_7.51.0.Final.html
- docs/overview_OpenRules_7.0.0.html
- docs/overview_Oracle Process Cloud_17.3.3.html
- docs/overview_Trisotech Digital Enterprise Suite_10.6.0.html
- docs/overview_jDMN_3.4.1.html
- docs/tests.html
- runners/dmn-tck-reporter/src/main/resources/templates/index.ftl
Usual refresh of the website.
In a couple of previous iterations, the website footer was reporting wrong links to archives and erroneously mentioning v1.2 instead of v1.3. I'm sorry for that. This should fix it going forward too.
> Publishing website for the results of Mar 2021

- TestCases/compliance-level-3/0080-feel-getvalue-function/0080-feel-getvalue-function-test-01.xml
- TestCases/compliance-level-3/0080-feel-getvalue-function/0080-feel-getvalue-function.dmn
- TestCases/compliance-level-3/0081-feel-getentries-function/0081-feel-getentries-function-test-01.xml
- TestCases/compliance-level-3/0081-feel-getentries-function/0081-feel-getentries-function.dmn
the `entries()` and `get value()` functions were kind of only half in the 1.2 spec.  We had tests for them but not for named params - they were commented out because (if I recall) those names were not yet official, or something. Those tests are now uncommented here. Plus, I've added two tests for the `get value` function that assert it will accept a non-literal string key name - all existing tests were providing a literal string 'key' param and for those that implement type inference here based on the literal key name and its corresponding type in the context - it could be a gotcha. 
Apols for the inexactly named branch.
> DMN1-3 context functions

- TestCases/compliance-level-3/0082-feel-coercion/0082-feel-coercion.dmn
- TestCases/compliance-level-3/0086-import/Imported_Model.dmn
- TestCases/compliance-level-3/0087-chapter-11-example/0087-chapter-11-example.dmn
- TestCases/non-compliant/0019-flight-rebooking/0019-flight-rebooking.dmn
@StrayAlien @tarilabs 
Based on the discussions we had as part of PR #385 I believe that:
1. `bkm.variable.typeRef` and `bkm.encapsulatedLogic.typeRef`, when present should be function type
2. `bkm.encapsultatedLogic.expression.typeRef` (function definition body) is the output type of the BKM
Looking forward for your comments.
Octavian
> Fix typeRef for bkmn.encapsulatedLogic

- README.md
- docs/about.html
- docs/detail_ACTICO Platform_8.1.5.html
- docs/detail_Camunda DMN-Scala Extension_1.7.0.html
- docs/detail_Digital Transformation Platform (DXP)_2.4.html
- docs/detail_Drools_7.58.0.Beta1.html
- docs/detail_OpenRules_7.0.0.html
- docs/detail_Oracle Process Cloud_17.3.3.html
- docs/detail_Trisotech Digital Enterprise Suite_10.11.0.html
- docs/detail_jDMN_5.0.0.html
- docs/glossary.html
- docs/index.html
- docs/overview_ACTICO Platform_8.1.5.html
- docs/overview_Camunda DMN-Scala Extension_1.7.0.html
- docs/overview_Camunda Platform_7.15.0.html
- docs/overview_Digital Transformation Platform (DXP)_2.4.html
- docs/overview_Drools_7.58.0.Beta1.html
- docs/overview_OpenRules_7.0.0.html
- docs/overview_Oracle Process Cloud_17.3.3.html
- docs/overview_Trisotech Digital Enterprise Suite_10.11.0.html
- docs/overview_jDMN_5.0.0.html
- docs/tests.html
- runners/dmn-tck-reporter/src/main/java/org/omg/dmn/tck/AboutGenerator.java
- runners/dmn-tck-reporter/src/main/java/org/omg/dmn/tck/Reporter.java
- runners/dmn-tck-reporter/src/main/resources/templates/about.ftl
- runners/dmn-tck-reporter/src/main/resources/templates/detail.ftl
- runners/dmn-tck-reporter/src/main/resources/templates/glossary.ftl
- runners/dmn-tck-reporter/src/main/resources/templates/index.ftl
- runners/dmn-tck-reporter/src/main/resources/templates/overview.ftl
- runners/dmn-tck-reporter/src/main/resources/templates/tests.ftl
(had inadvertently touched the Return key too soon).
This updates this repo README.md and creates a website About page with aligned information.
I seized the chance to implement suggestion from Denis and James, incorporating materials also from past TCK presentations at various conferences like Keith, in order to valorise all contributions as possible.
example:
The website is refreshed to give opportunity to share the about.html link.
> DMN TCK About page (README.md and website about.html)

- TestCases/compliance-level-3/0099-arithmetic-negation/0099-arithmetic-negation-test-01.xml
- TestCases/compliance-level-3/0099-arithmetic-negation/0099-arithmetic-negation.dmn
Some specific tests re arithmetic negation.  Just asserting what types may be negated.  And negation of already negated stuff.
There is one thing I'd like to highlight about arithmetic negation and my feeling is it is an oversight and may need to go for clarification and that is this in the S-FEEL section 9.5:
> Arithmetic negation (grammar rule 2.d) is defined only when its operand is a number: in that case, its semantics is
according to the specification of op:numeric-unary-minus
The same 'number' restriction is not mentioned in the FEEL (proper) section.
But as of 1.3 .. both duration types are now supported by abs() .  They already are supported by multiplications, so `@"P1D" * -1` is `-P1D` - arithmetic negation is effectively the same thing.  Indeed, a runtime is likely to implement …
> 0099-arithmetic-negation

- TestCases/compliance-level-3/0074-feel-properties/0074-feel-properties-test-01.xml
- TestCases/compliance-level-3/0074-feel-properties/0074-feel-properties.dmn
Assertions on the new 1.3 range properties for both range syntaxes.
Note the unary style syntax are disambiguated with ().  Otherwise, the dot property will be taken to be part of the end range expression.
> DMN1-3 range properties

- TestCases/compliance-level-3/0103-feel-is-function/0103-feel-is-function-test-01.xml
- TestCases/compliance-level-3/0103-feel-is-function/0103-feel-is-function.dmn
All, an initial suite of tests for the new DMN 1.3 is() function.  
This guy is not very well specified at all and it is not very clear what boundaries are on this guy - type the types it can operate on and so forth.  I have raised a issue with DMN seeking clarification.
But, I have some some assumptions that it operates on the types in section in 10.3.2.2 Equality, Identity and Equivalence.  To that end I have no tests covering other types until we know more.
Also, one thing in these tests is the notions that for types with zone/offset info, for the purposes of semantic equivalence we are interested in the _offset_.  The semantic fields given in 10.3.2.2 refer to an optional _offset_. So, two values being equal in all respects except for zone/offset will be semantically equal if they …
> DMN1-3 feel is function.

- TestCases/compliance-level-3/0072-feel-in/0072-feel-in-test-01.xml
- TestCases/compliance-level-3/0072-feel-in/0072-feel-in.dmn
Some additional assertions on what happens when nulls are part of ranges and when endpoints are null-coerced and incompatible.
The unary syntax for range and equivalence thereof with the non unary syntax kind of means non unary ranges can act like unary ranges.
Note the specs do not seem to support the usage on a unary syntax range with the 'in' keyword, so no assertions for that are made here - just what happens with nulls in non-unary ranges.
Comments welcome.
> DMN1-3 feel in

- TestCases/compliance-level-3/0082-feel-coercion/0082-feel-coercion-test-01.xml
- TestCases/compliance-level-3/0082-feel-coercion/0082-feel-coercion.dmn
- TestCases/compliance-level-3/0085-decision-services/0085-decision-services-test-01.xml
As per recent discussions that an invocation with params that do not conform to the to-be-invoked-function formal param types, or has unknown named params, will 'short-circuit' to null and the actual target of invocation will never be executed ...
Here are some fixups in the TCK to reflect that.  
As a boxed Invocation is really a function call with named params and therefore (IMO) also subject to the same conditions as any other invocation with named params I've added one extra test to assert that same null result.
All comments and feedback welcome. 
PS: I apologise for the 'noise' with the spaces but I have git config set at `core.autocrlf input` as per guidelines for mac/linux.
> corrections and assertions on invalid params

- TestCases/compliance-level-3/0070-feel-instance-of/0070-feel-instance-of-test-01.xml
- TestCases/compliance-level-3/0070-feel-instance-of/0070-feel-instance-of.dmn
DMN 1.3 instance of changes - and some stuff
Some previously-commented tests have been uncommented now that types are a supported syntax. 
A series of tests for list, context and function type conformity.
Note (very oddly) there is no syntax in the DMN 1.3 spec for range types, so we officially can't check (say) if `[1..2] instance of range<number>`.
Also, it is not possible to check if something is simply a context or a function.  The described grammar for context requires _at least_ one property.  So, it is not possible to assert (say) `{foo: "bar"} instance of context`, or even worse, `{} instance of context`.  There seems to be no way to describe an empty context type.  So, that is a gap (correct me if I am wrong) and thus there are no assertions included here for same.
Re functions, …
> DMN 1.3 instance of

- TestCases/compliance-level-3/0091-local-hrefs/0091-local-hrefs-test-01.xml
- TestCases/compliance-level-3/0091-local-hrefs/0091-local-hrefs.dmn
re PR of here:  https://github.com/dmn-tck/tck/pull/356
When an element reference href contains a namespace like this "http://mynamespace#decision001" is it tempting to immediately consider it as an import even though the given namespace may be the current model namespace.
This PR has a single test that asserts that if a qualified href whose namespace refers to the current model then the reference is considered model-local and is effectively the same as having no namespace - like #decision001" in the above example.
Comments welcome.
Greg.
> 0091-local-hrefs

- TestCases/compliance-level-3/0057-feel-context/0057-feel-context-test-01.xml
- TestCases/compliance-level-3/0057-feel-context/0057-feel-context.dmn
Ensures the following is true:
```
{ a: 1 }.b = null
null.b = null
```
Related to https://github.com/dmn-tck/tck/issues/537
> test(feel): verify non-existing member access

- TestCases/testCases.xsd
The following attributes are added:
- TestCases.namespace - default namespace for all DRGElements referenced in the test file
- TestCase.namespace - default namespace for all DRGElements referenced in the test case
- InputNode.namespace - namespace for the DRGElement  referenced in the InputNode
- ResultNode.namespace - namespace for the DRGElement referenced in the ResultNode
The namespace defined at lower levels (e.g. InputNode) takes precedence over the ones defined at the higher levels (e.g. TestCases)
> Add 'namespace' attribute to disambiguate the DRGElement references

- TestCases/compliance-level-3/0063-feel-stddev-function/0063-feel-stddev-function-test-01.xml
- TestCases/compliance-level-3/0063-feel-stddev-function/0063-feel-stddev-function.dmn
test description said it was expecting a non-null value - which is incorrect.  Also, another test in there to cover the example in the spec of a singleton list as a param.
> amend incorrect stddev test description and add additional test for singleton list as per spec example

- TestCases/compliance-level-3/1156-range-function/1156-range-function-test-01.xml
- TestCases/compliance-level-3/1156-range-function/1156-range-function.dmn
The new range function gets exercised.  The spec is very specific about what can be passed to this function as a string.  These tests seek to cover all that.
Like:
* the grammar only permits literal as endpoints.  If permits function calls if they are the date/time literal functions.  Nothing else.  No build in functions, not any other function the returns a string/number/date/time/duration value.  Just literals and literal functions.
* The grammar only permits range expressions with a '..' in them .. so no unary style range like range("<10").  All grammar optional have a range start character, and a range end character.  But, under some circumstances either the start or the end endPoint may be omitted.
I understand there is a PR in already for the range function but (apols …
> DMN 1.5 - 1156-range-function

- TestCases/compliance-level-3/0068-feel-equality/0068-feel-equality-test-01.xml
- TestCases/compliance-level-3/0068-feel-equality/0068-feel-equality.dmn
Not very exciting, but, some tests for numbers with exponents.  
Without trying to replicate a while load of number tests I thought perhaps it easier just to test that the 'e' number and its not 'e' version are actually equal.  Then, the rest is assumed .... we've proven it is a number ...
> DMN 1.5 - 'e' number equivalence

- TestCases/compliance-level-3/0084-feel-for-loops/0084-feel-for-loops-test-01.xml
- TestCases/compliance-level-3/0084-feel-for-loops/0084-feel-for-loops.dmn
Dates may now be used by loops.  Some simple tests for prove this is possible and that the increment is by a single day
> DMN 1.5 - date increments in loops

- TestCases/compliance-level-3/1155-list-replace-function/1155-list-replace-function-test-01.xml
- TestCases/compliance-level-3/1155-list-replace-function/1155-list-replace-function.dmn
Suite of pretty standard tests for the new "list replace" function.  Exercises good/bad positional and named params.  Also negative positioning.
> DMN 1.5 - 1155-list-replace-function

- runners/dmn-tck-runner-drools/src/test/java/org/omg/dmn/tck/runner/drools/DroolsTCKTest.java
Tests 0092 and 1131 of TCK Tests suite are not executed because a failure occurs during the compilation of the related DMN files.
Those DMN files contain references to unexisting functions, so it's expected that the compilation fail.
As the TCK Tests suite is relying on the "old" KieContainer API, is not possible to separate the compilation and the execution phases.
So, the solution is to use the "new" API layer that doesn't have this strict phase management
@baldimir @gitgabrio
Before this change:
`[ERROR] Tests run: 6618, Failures: 0, Errors: 36, Skipped: 0`
After this change:
`[ERROR] Tests run: 6667, Failures: 0, Errors: 35, Skipped: 0`
`
> Drools - Fix TCK tests failing because of a compilation failure

- TestCases/compliance-level-3/0084-feel-for-loops/0084-feel-for-loops-test-01.xml
- TestCases/compliance-level-3/0084-feel-for-loops/0084-feel-for-loops.dmn
This is related to https://github.com/dmn-tck/tck/issues/681
According to Section 10.3.2.14, range expressions are not allowed as iteration context. For example, 1..2 is supported but not (1..2]
> An iteration context may either be an expression that returns a list of elements, or two expressions that return integers connected by “..”.
> Change 'for loop' tests to match semantics in Section 10.3.2.14

- TestCases/compliance-level-3/0074-feel-properties/0074-feel-properties-test-01.xml
- TestCases/compliance-level-3/0074-feel-properties/0074-feel-properties.dmn
I have changed the structure of the tests to make then less spread out.  In effect, each range test asserts on a context of its property values.  Keeps stuff together.  All the previous test assertions are still here.
The values I am asserting on here are:
| expression | start included | start | end | end included |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| =10  | true | 10 | 10 | true |
| !=10  | false  | 10 | 10 | false |
This is not covered in the spec, so, comments welcome.
> DMN 1.5 - extra assertions for the range properties for `=` and `!=`.  
