dmn-tck/tck

- TestCases/compliance-level-2/0105-feel-math/0105-feel-math-test-01.xml
As discussed in the meeting, adding the xsi:nil attribute to test case 0105.
> Adding xsi:nil attributes to test case 0105

- TestCases/compliance-level-3/0021-singleton-list/0021-singleton-list-test-01.xml
- TestCases/compliance-level-3/0021-singleton-list/0021-singleton-list.dmn
As discussed in the meeting, this test adds checks for the coercion from singleton lists into single elements depending on the context of the test.
The first 4 decisions (decision 1 through 4) check for coercion based on the variable type. Decision 5 checks for coercion during function invocation.
> Adding test case 0021 to test for singleton list coercion

- TestCases/compliance-level-3/0008-listGen/0008-listGen-test-01.xml
- TestCases/compliance-level-3/0012-list-functions/0012-list-functions-test-01.xml
Split 0008-listGen-test-01 and 0012-list-functions-test-01
> Split more test cases for more detailed reporing

- utils/dmn-tck-packager/README.md
- utils/dmn-tck-packager/pom.xml
- utils/dmn-tck-packager/src/main/java/org/dmn/tck/packager/CommandLinePackager.java
- utils/dmn-tck-packager/src/main/java/org/dmn/tck/packager/Packager.java
I'm contributing a small utility to package/extract DMN TCK test cases from/to a DMN XML
> Initial revision of the DMN TCK Packager

- TestCases/testCases.xsd
- runners/dmn-tck-marshaller/src/main/java/org/omg/dmn/tck/validation/SchemaValidator.java
This is to add missing nillable attribute and a schema validation.
Once this is agreed we need to update the ValueType java class to reflect the change.
> Add schema validation and fix TestCases.xsd

- runners/dmn-tck-runner/src/main/java/org/omg/dmn/tck/runner/junit4/DmnTckRunner.java
Had some issues when running on Windows
Thanks.
> Fix the \ vs / issue in the test results

- TestCases/compliance-level-3/1116-feel-time-function/1116-feel-time-function-test-01.xml
- TestCases/compliance-level-3/1116-feel-time-function/1116-feel-time-function.dmn
- TestCases/compliance-level-3/1116-feel-time-function/Readme.md
- TestCases/testCases.xsd
Adding testcases for FEEL time() function including error scenarios. 
Requires #79 to be merged first.
> TestCases for FEEL time() function tests

- TestCases/compliance-level-3/1115-feel-date-function/1115-feel-date-function-test-01.xml
- TestCases/compliance-level-3/1116-feel-time-function/1116-feel-time-function-test-01.xml
- TestCases/compliance-level-3/1117-feel-date-and-time-function/1117-feel-date-and-time-function-test-01.xml
- TestCases/compliance-level-3/1120-feel-duration-function/1120-feel-duration-function-test-01.xml
- TestCases/compliance-level-3/1121-feel-years-and-months-duration-function/1121-feel-years-and-months-duration-function-test-01.xml
1117-feel-date-and-time-function, test 57
see PR #95
1121-feel-years-and-months-duration-function, tests 31 and 32
see PR #96
1115-feel-date-function, tests 030 051
1116-feel-time-function, tests 078 084 085
1120-feel-duration-function, tests 048 049 050 054 055 056 057
these tests need to be discussed on the next TCK meeting
> Remove from results-2017-11 branch tests to be discussed at TCK meeting

- TestCases/compliance-level-2/0009-invocation-arithmetic/0009-invocation-arithmetic.dmn
- TestCases/compliance-level-3/0003-iteration/0003-iteration.dmn
- TestCases/compliance-level-3/0004-lending/0004-lending.dmn
- TestCases/compliance-level-3/0005-literal-invocation/0005-literal-invocation.dmn
- TestCases/compliance-level-3/0014-loan-comparison/0014-loan-comparison.dmn
- TestCases/compliance-level-3/0016-some-every/0016-some-every.dmn
- TestCases/compliance-level-3/0031-user-defined-functions/0031-user-defined-functions.dmn
- TestCases/compliance-level-3/0033-for-loops/0033-for-loops.dmn
Moved typeRef attribute of business knowledge model information item to body expression of function definition.
> Moved typeRef attribute of business knowledge model information item to body expression of function definition

- README.md
as discussed in today's meeting
> Add instructions on how to run Java-based runners

- TestCases/compliance-level-3/0035-test-structure-output/0035-test-structure-output.dmn
Addresses https://github.com/dmn-tck/tck/issues/158
I'm sorry to have missed this, @DanielThanner .
/cc @etirelli can you review please? Thx.
> Remove any typeRefs for BKMs inside 0035-test-structure-output

- runners/dmn-tck-runner-drools/src/test/java/org/omg/dmn/tck/runner/drools/DroolsTCKTest.java
https://issues.jboss.org/browse/DROOLS-2620
1. it is generating the results file on the same folder as the
project. We need to change that to generate the file on the proper
TestResults/Drools... folder.
2. when generating the results file, it should also update the date
inside the tck_results.properties file.
3. finally, if a new version is used, it should remove the files from
previous versions.
> DROOLS-2620 Update drools TCK runner

- TestCases/binding.xjb
- TestCases/testCases.xsd
That support vendor extensions and a name (optional) attribute on TestCase
> New Test Case Schema #176

- runners/dmn-tck-reporter/src/main/java/org/omg/dmn/tck/Reporter.java
- runners/dmn-tck-reporter/src/main/java/org/omg/dmn/tck/TestResult.java
- runners/dmn-tck-reporter/src/main/resources/templates/detail.ftl
- runners/dmn-tck-reporter/src/main/resources/templates/index.ftl
- runners/dmn-tck-reporter/src/main/resources/templates/overview.ftl
@tarilabs @agilepro @DanielThanner 
As discussed in the meetings, this ticket is updating the website generation script to report test results based on the approved list from ticket #165 .
> Issue #165: updating website generation script to report missing and not supported features

- runners/dmn-tck-runner-drools/src/test/java/org/omg/dmn/tck/runner/drools/DroolsTCKTest.java
When a DMNType is not available to unmarshal TCK test expected value,
use inference heuristics based on JAXB value type.
> Drools DMN TCK runner improvements

- runners/dmn-tck-runner-drools/src/test/java/org/omg/dmn/tck/runner/drools/DroolsTCKTest.java
> Drools runner improvements.

- runners/dmn-tck-runner-drools/src/test/java/org/omg/dmn/tck/runner/drools/DroolsTCKTest.java
> Drools runner improvements

- TestCases/compliance-level-3/0050-feel-abs-function/0050-feel-abs-function-test-01.xml
- TestCases/compliance-level-3/0050-feel-abs-function/0050-feel-abs-function.dmn
- TestCases/compliance-level-3/0051-feel-sqrt-function/0051-feel-sqrt-function-test-01.xml
- TestCases/compliance-level-3/0051-feel-sqrt-function/0051-feel-sqrt-function.dmn
- TestCases/compliance-level-3/0052-feel-exp-function/0052-feel-exp-function-test-01.xml
- TestCases/compliance-level-3/0052-feel-exp-function/0052-feel-exp-function.dmn
- TestCases/compliance-level-3/0053-feel-log-function/0053-feel-log-function-test-01.xml
- TestCases/compliance-level-3/0053-feel-log-function/0053-feel-log-function.dmn
- TestCases/compliance-level-3/0054-feel-even-function/0054-feel-even-function-test-01.xml
- TestCases/compliance-level-3/0054-feel-even-function/0054-feel-even-function.dmn
- TestCases/compliance-level-3/0055-feel-odd-function/0055-feel-odd-function-test-01.xml
- TestCases/compliance-level-3/0055-feel-odd-function/0055-feel-odd-function.dmn
- TestCases/compliance-level-3/0056-feel-modulo-function/0056-feel-modulo-function-test-01.xml
- TestCases/compliance-level-3/0056-feel-modulo-function/0056-feel-modulo-function.dmn
- TestCases/compliance-level-3/0062-feel-mode-function/0062-feel-mode-function-test-01.xml
- TestCases/compliance-level-3/0062-feel-mode-function/0062-feel-mode-function.dmn
- TestCases/compliance-level-3/0063-feel-stddev-function/0063-feel-stddev-function-test-01.xml
- TestCases/compliance-level-3/0063-feel-stddev-function/0063-feel-stddev-function.dmn
- TestCases/compliance-level-3/0064-feel-conjunction/0064-feel-conjunction-test-01.xml
- TestCases/compliance-level-3/0064-feel-conjunction/0064-feel-conjunction.dmn
- TestCases/compliance-level-3/0065-feel-disjunction/0065-feel-disjunction-test-01.xml
- TestCases/compliance-level-3/0065-feel-disjunction/0065-feel-disjunction.dmn
- TestCases/compliance-level-3/0066-feel-negation/0066-feel-negation-test-01.xml
- TestCases/compliance-level-3/0066-feel-negation/0066-feel-negation.dmn
Covering suites:
0050-feel-abs-function
0051-feel-sqrt-function
0052-feel-exp-function
0053-feel-log-function
0054-feel-even-function
0055-feel-odd-function
0056-feel-modulo-function
0062-feel-mode-function
0063-feel-stddev-function
0064-feel-conjunction
0065-feel-disjunction
0066-feel-negation
ref: https://github.com/dmn-tck/tck/pull/204#issuecomment-456006225
> Consolidated PR of approved-so-far tests.

- TestCases/compliance-level-3/0074-feel-properties/0074-feel-properties-test-01.xml
- TestCases/compliance-level-3/0074-feel-properties/0074-feel-properties.dmn
Added missing error flags and fixed the zone IDs
> 0074-feel-properties

- TestCases/compliance-level-3/0004-lending/0004-lending.dmn
Small correction of some types from "string" to what they actually represent in the model, "boolean", "number" etc.
This was originally in the big 'consolidated' PR but got lost when we split them up.
https://github.com/dmn-tck/tck/pull/204#issuecomment-448089266
> 0004-lending

- TestCases/compliance-level-3/0083-feel-unicode/0083-feel-unicode-test-01.xml
- TestCases/compliance-level-3/0083-feel-unicode/0083-feel-unicode.dmn
It was raised during the TCK meeting 2019-05-11 the result is debatable
for these specific tests, on the basis of
https://issues.omg.org/issues/DMN13-127
ref
https://github.com/dmn-tck/tck/pull/239#issuecomment-490156355
> 0083-unicode some tests commented out as decision TCK meeting 2019-05-11

- TestCases/compliance-level-3/0072-feel-in/0072-feel-in-test-01.xml
- TestCases/compliance-level-3/0072-feel-in/0072-feel-in.dmn
It was raised to my attention a test which was subject of debate was not
commented out on master. Test pull aside to continue discussion
ref
https://github.com/dmn-tck/tck/pull/228#issuecomment-462135835
/cc @opatrascoiu @StrayAlien @agilepro
> 0072-feel-in some tests // as decision TCK meeting 2019-05-11

- runners/dmn-tck-runner-drools/src/test/java/org/omg/dmn/tck/runner/drools/DroolsTCKTest.java
Requires https://github.com/dmn-tck/tck/pull/291
Please DO NOT MERGE until https://github.com/dmn-tck/tck/pull/291 is merged first.
> Drools TCKTest runner specific support to TCK import API features

- runners/dmn-tck-runner-drools/src/test/java/org/omg/dmn/tck/runner/drools/DroolsTCKTest.java
> Drools runner update following https://github.com/dmn-tck/tck/pull/308

- TestCases/compliance-level-3/0086-import/0086-import-test-01.xml
- TestCases/compliance-level-3/0086-import/0086-import.dmn
- TestCases/compliance-level-3/0086-import/Imported_Model.dmn
As requested on https://github.com/dmn-tck/tck/pull/291#issuecomment-489165162
> 0086-import new test case

- TestCases/compliance-level-3/0089-nested-inputdata-imports/0089-nested-inputdata-imports-test-01.xml
- TestCases/compliance-level-3/0089-nested-inputdata-imports/0089-nested-inputdata-imports.dmn
- TestCases/compliance-level-3/0089-nested-inputdata-imports/Model_B.dmn
- TestCases/compliance-level-3/0089-nested-inputdata-imports/Model_B2.dmn
- TestCases/compliance-level-3/0089-nested-inputdata-imports/Say_hello_1ID1D.dmn
Test case proposal to resolve #274
> Test case demonstrating InputData with imports, and imports of imports

- docs/detail_ACTICO Platform_8.1.5.html
- docs/detail_Camunda BPM_7.9.0.html
- docs/detail_Digital Transformation Platform (DXP)_2.4.html
- docs/detail_Drools_7.30.0.Final.html
- docs/detail_OpenRules_7.0.0.html
- docs/detail_Oracle Process Cloud_17.3.3.html
- docs/detail_Trisotech DMN Modeler_6.2.7.html
- docs/detail_jDMN_3.3.0.html
- docs/glossary.html
- docs/index.html
- docs/overview_ACTICO Platform_8.1.5.html
- docs/overview_Camunda BPM_7.9.0.html
- docs/overview_Digital Transformation Platform (DXP)_2.4.html
- docs/overview_Drools_7.30.0.Final.html
- docs/overview_OpenRules_7.0.0.html
- docs/overview_Oracle Process Cloud_17.3.3.html
- docs/overview_Trisotech DMN Modeler_6.2.7.html
- docs/overview_jDMN_3.3.0.html
- docs/tests.html
(website refresh, no results update)
> Publish website for the results of the month 2019-12

- runners/dmn-tck-runner-drools/src/test/java/org/omg/dmn/tck/runner/drools/DroolsTCKTest.java
Align to TCK semantic of TCK errorFlag
> Drools runner update to consistency of TCK errorResult flag

- docs/detail_ACTICO Platform_8.1.5.html
- docs/detail_Camunda BPM_7.13.0.html
- docs/detail_Digital Transformation Platform (DXP)_2.4.html
- docs/detail_Drools_7.48.0.Final.html
- docs/detail_OpenRules_7.0.0.html
- docs/detail_Oracle Process Cloud_17.3.3.html
- docs/detail_Trisotech Digital Enterprise Suite_10.4.0.html
- docs/detail_jDMN_3.4.1.html
- docs/glossary.html
- docs/index.html
- docs/overview_ACTICO Platform_8.1.5.html
- docs/overview_Camunda BPM_7.13.0.html
- docs/overview_Digital Transformation Platform (DXP)_2.4.html
- docs/overview_Drools_7.48.0.Final.html
- docs/overview_OpenRules_7.0.0.html
- docs/overview_Oracle Process Cloud_17.3.3.html
- docs/overview_Trisotech Digital Enterprise Suite_10.4.0.html
- docs/overview_jDMN_3.4.1.html
- docs/tests.html
> Publishing website for the results of Jan 2021

- TestCases/compliance-level-3/1130-feel-interval/1130-feel-interval-test-01.xml
- TestCases/compliance-level-3/1130-feel-interval/1130-feel-interval.dmn
New test case that validate the DMN 1.3 newly introduced interval functions
> New tests case for DMN 1.3 interval functions

- TestCases/compliance-level-3/0050-feel-abs-function/0050-feel-abs-function-test-01.xml
- TestCases/compliance-level-3/0050-feel-abs-function/0050-feel-abs-function.dmn
Assertions on the new support for durations.  Also, removed typeRefs from variables - they're serving no purpose here.
> DMN 1.3 abs

- TestCases/compliance-level-3/0083-feel-unicode/0083-feel-unicode-test-01.xml
- TestCases/compliance-level-3/0083-feel-unicode/0083-feel-unicode.dmn
Some additional assertions on the new 6 digit unicode.  Maybe waaay less than required for such a topic, but something is better than nothing.  Hopefully I got it right .... 
comments welcome.
> DMN1-3 unicode

- TestCases/compliance-level-3/0093-feel-at-literals/0093-feel-at-literals-test-01.xml
- TestCases/compliance-level-3/0093-feel-at-literals/0093-feel-at-literals.dmn
assertion on the new @ literal syntax
> DMN 1.3 0093-feel-at-literals

- runners/dmn-tck-runner-drools/src/test/java/org/omg/dmn/tck/runner/drools/DroolsTCKTest.java
Fix proper deserialization from DMN TCK xml file using appropriate JAXB api.
> Drools runner update jaxb

- TestCases/compliance-level-3/0094-feel-product-function/0094-feel-product-function-test-01.xml
- TestCases/compliance-level-3/0094-feel-product-function/0094-feel-product-function.dmn
Not a DMN 1.3 thing, but we had no coverage on this guy.
> 0094-feel-product-function

- TestCases/compliance-level-3/0092-feel-lambda/0092-feel-lambda.dmn
ref https://github.com/dmn-tck/tck/issues/430#issuecomment-822363590
> Address #430 in TestCases/compliance-level-3/0092-feel-lambda

- TestCases/compliance-level-3/0082-feel-coercion/0082-feel-coercion.dmn
- TestCases/non-compliant/0019-flight-rebooking/0019-flight-rebooking.dmn
as they relate to Invokables/FunctionDefinition/typeRefs.
https://github.com/dmn-tck/tck/pull/423.
I apologies for the spaces changes.  I've undid them locally to have just the valid lines change but it could be a mac / windows thing.  I'm on a mac with git settings to interact nicely with windows.  Dunno.
The changes here deal with types on the variable, not on the encapsulated logic.  The type for tDS_001 has been changed to a function type to keep the intention of the test intact.
Comment welcome.
> Small update on PR 423 to adjust some function typings 

- TestCases/compliance-level-3/0057-feel-context/0057-feel-context-test-01.xml
results in null and error
see https://issues.omg.org/browse/DMN14-178
Resolves #400
> Context entry with dup keys result not allowed

- runners/dmn-tck-marshaller/pom.xml
> Update TCK infra with JDK 17 compatibility

- .github/workflows/global_validation.yml
- .github/workflows/optional_camunda-dmn-scala.yml
- .github/workflows/optional_camunda.yml
- .github/workflows/optional_drools.yml
- runners/dmn-tck-marshaller/pom.xml
- runners/dmn-tck-reporter/pom.xml
- runners/dmn-tck-runner-camunda-dmn-scala/pom.xml
- runners/dmn-tck-runner-camunda/pom.xml
- runners/dmn-tck-runner-drools/pom.xml
- runners/dmn-tck-runner-trisotech/pom.xml
- runners/dmn-tck-runner/pom.xml
- runners/pom.xml
- utils/dmn-tck-packager/pom.xml
* updating github action
* updating pom.xml
>  update to Java 11 version

- TestCases/compliance-level-3/0082-feel-coercion/0082-feel-coercion.dmn
The "list" typeRef is missing - is not defined as ItemDefinition or in FEEL.
> Fix incorrect typeRef

- runners/dmn-tck-reporter/src/main/java/org/omg/dmn/tck/Reporter.java
- runners/dmn-tck-reporter/src/main/resources/templates/detail.ftl
- runners/dmn-tck-reporter/src/main/resources/templates/tests.ftl
This PR fixes both #562 and #563 
Discovered the issues when updating the reporting changes
> Issues 562 563

- TestCases/compliance-level-3/1148-feel-now-function/1148-feel-now-function-test-01.xml
- TestCases/compliance-level-3/1148-feel-now-function/1148-feel-now-function.dmn
not a lot to test here.  We can't mock the current date/time, so, just asserting on return type. :-(
> DMN 1.4 - 1148-feel-now-function

- TestCases/compliance-level-3/1131-feel-function-invocation/1131-feel-function-invocation-test-01.xml
- TestCases/compliance-level-3/1131-feel-function-invocation/1131-feel-function-invocation.dmn
Yields `null`.
----
Closes https://github.com/dmn-tck/tck/issues/539
> test: verify non-existing function invocation

- utils/dmn-tck-packager/README.md
Added more detail on the extension mechanism used by this utility to support the DMN RTF issue: https://issues.omg.org/browse/DMN16-6
> Improved the dmn-tck-packager readme

- runners/dmn-tck-validation/src/test/java/org/omg/dmn/tck/validation/TestCasesFiles.java
Check constraints:
DRGElement.name == DRGElement.variable.name and DRGElement.typeRef == DRGElement.variable.typeRef
> Add extra validation for DRGElements

- TestCases/compliance-level-3/1101-feel-floor-function/1101-feel-floor-function-test-01.xml
- TestCases/compliance-level-3/1101-feel-floor-function/1101-feel-floor-function.dmn
Updated for 1.4 additions. Also, revamped to include tests for named params, bad params, too many params etc. Some of the old tests were redundant, but, I've kept the ones that matter. There weren't many anyways.
No tests here as yet for negative scales. That will likely be a separate PR.
> DMN 1.4 - 1101-feel-floor-function

- runners/dmn-tck-validation/src/test/java/org/omg/dmn/tck/validation/TestCasesFiles.java
Remove check for typeRef as the attribute is not present for DRG Elements
> Fix validation for DRGElements

- TestCases/compliance-level-3/0099-arithmetic-negation/0099-arithmetic-negation-test-01.xml
- TestCases/compliance-level-3/0099-arithmetic-negation/0099-arithmetic-negation.dmn
Uncommenting some tests that assert on arithmetic negation of durations.  1.5 now permits this.  
ref for conv re commenting them out: https://github.com/dmn-tck/tck/pull/401#issuecomment-962982239
> DMN 1.5 - arithmetic negation of durations

- TestCases/compliance-level-3/0068-feel-equality/0068-feel-equality-test-01.xml
- TestCases/compliance-level-3/0068-feel-equality/0068-feel-equality.dmn
This is related to https://github.com/dmn-tck/tck/issues/682
More info in the issue.
> Change tests to reflect the intention expressed in comments

- .github/workflows/global_validation.yml
- .github/workflows/optional_camunda-dmn-scala.yml
- .github/workflows/optional_camunda.yml
- .github/workflows/optional_drools.yml
- .github/workflows/optional_jdmn.yml
- .github/workflows/report.yml
This should hopefully fix the PR checks.
> Upgrade plugins in GitHub Actions.
